### ISSUE TITLE
tag v.2

### ISSUE THREAD

**Issue by dave3d** [SimpleITK/CommentSpellCheck#46]
@jcfr @jhlegarreta Have you guys finished your updates to the code for now?  If so, we'll tag a new version.  If not, we can wait.

**Comment by jhlegarreta** [comment]
I do not have ongoing PRs or any other updates in my pipeline. Thanks @dave3d.

**Comment by jcfr** [comment]
No problem for releasing `v0.2`.

Anticipating, that we will soon have the package released on PyPI, I would suggest to instead create the tag as `v0.2.0`.

This will be consistent with versioning practices:
* https://py-pkgs.org/07-releasing-versioning.html#version-numbering
* https://blog.inedo.com/python/best-practices-for-versioning-python-packages-in-the-enterprise/
* https://learn.scientific-python.org/development/tutorials/packaging/
* https://semver.org/
