### ISSUE TITLE
Please warn when a dictionary entry has any non-alphabetic character

### ISSUE THREAD

**Issue by N-Dekker** [SimpleITK/CommentSpellCheck#54]
It appears that a dictionary entry that any non-alphabetic character is ignored. (Please correct me if I'm wrong.) For example, adding `cert-dcl58-cpp` to https://github.com/InsightSoftwareConsortium/ITK/blob/042d42327bd299e66a3cfd5c6fed169fd5c8aa95/.github/workflows/itk_dict.txt did not help to stop the detection of misspellings in a text like:

    // > warning: modification of 'std' namespace can result in undefined behavior [cert-dcl58-cpp]

In order to reduce the time spent on trial and error, it would be helpful if CommentSpellCheck would produce a warning when a dictionary entry has any non-alphabetic character. It would be nice if CommentSpellCheck  would then specifically mention the dictionary entry.

**Comment by dave3d** [comment]
@N-Dekker 
The following PR addresses this issue;
https://github.com/SimpleITK/CommentSpellCheck/pull/55
